import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import type { Batch, Profile } from "@/types";

// Register a font (Helvetica is always available)
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 2,
    borderBottomColor: "#D97706",
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#D97706",
  },
  subtitle: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 4,
  },
  breweryName: {
    fontSize: 14,
    marginTop: 10,
    color: "#1F2937",
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#1F2937",
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    paddingBottom: 4,
  },
  row: {
    flexDirection: "row",
    marginBottom: 6,
  },
  label: {
    width: 120,
    color: "#6B7280",
    fontWeight: "bold",
  },
  value: {
    flex: 1,
    color: "#1F2937",
  },
  gravityGrid: {
    flexDirection: "row",
    gap: 10,
    marginVertical: 12,
  },
  gravityBox: {
    flex: 1,
    padding: 12,
    backgroundColor: "#F3F4F6",
    borderRadius: 4,
    alignItems: "center",
  },
  gravityLabel: {
    fontSize: 10,
    color: "#6B7280",
    textTransform: "uppercase",
  },
  gravityValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1F2937",
    marginTop: 4,
  },
  abvBox: {
    flex: 1,
    padding: 12,
    backgroundColor: "#FFFBEB",
    borderRadius: 4,
    borderColor: "#D97706",
    borderWidth: 1,
    alignItems: "center",
  },
  notesSection: {
    marginTop: 20,
    padding: 12,
    backgroundColor: "#F9FAFB",
    borderRadius: 4,
  },
  notesLabel: {
    fontSize: 10,
    color: "#6B7280",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  notesText: {
    fontSize: 10,
    color: "#374151",
    lineHeight: 1.5,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    color: "#9CA3AF",
    fontSize: 9,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    paddingTop: 10,
  },
});

interface BatchPDFProps {
  batch: Batch;
  profile: Profile;
}

export function BatchPDF({ batch, profile }: BatchPDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>🍺 BrewLog.ai</Text>
          <Text style={styles.subtitle}>Batch Report</Text>
          {profile.brewery_name && (
            <Text style={styles.breweryName}>{profile.brewery_name}</Text>
          )}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Batch Information</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Beer Name</Text>
            <Text style={styles.value}>{batch.beer_name}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Batch Number</Text>
            <Text style={styles.value}>#{batch.batch_number}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Date</Text>
            <Text style={styles.value}>
              {new Date(batch.date).toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
            </Text>
          </View>
        </View>

        <View style={styles.gravityGrid}>
          <View style={styles.gravityBox}>
            <Text style={styles.gravityLabel}>OG</Text>
            <Text style={styles.gravityValue}>
              {batch.og ?? "—"}
            </Text>
          </View>
          <View style={styles.gravityBox}>
            <Text style={styles.gravityLabel}>FG</Text>
            <Text style={styles.gravityValue}>
              {batch.fg ?? "—"}
            </Text>
          </View>
          <View style={styles.abvBox}>
            <Text style={styles.gravityLabel}>ABV</Text>
            <Text style={[styles.gravityValue, { color: "#D97706" }]}>
              {batch.abv ? `${batch.abv}%` : "—"}
            </Text>
          </View>
        </View>

        {batch.notes && (
          <View style={styles.notesSection}>
            <Text style={styles.notesLabel}>Notes</Text>
            <Text style={styles.notesText}>{batch.notes}</Text>
          </View>
        )}

        <Text style={styles.footer}>
          Generated by BrewLog.ai on{" "}
          {new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </Text>
      </Page>
    </Document>
  );
}
